# Site
site: "Xinhai Chang"
title: "Xinhai Chang | 常欣海"
description: "Personal academic homepage of Xinhai Chang, Peking University."
repository: chang-xinhai/chang-xinhai.github.io
url: "https://chang-xinhai.github.io"
timezone: Asia/Shanghai

# Integrations
google_scholar_stats_use_cdn: false
google_analytics_id:
google_site_verification:
bing_site_verification:
baidu_site_verification:

# Author profile
author:
  name: "Xinhai Chang"
  avatar: "images/avatar/avatar.png"
  bio: "常欣海"
  location: "Beijing, China"
  googlescholar: "https://scholar.google.com/citations?user=NVxBzq4AAAAJ"
  email: "changxinhai@pku.edu.cn"
  researchgate: "https://www.researchgate.net/profile/Xinhai-Chang"
  github: chang-xinhai
  wechat: "images/wechat.png"
  cv: "/docs/CV_Xinhai_Chang.pdf"

# Build inputs
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Page defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# URLs and plugins
permalink: /:categories/:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML compression
compress_html:
  clippings: all
  ignore:
    envs: development
